DROP TABLE IF EXISTS questions;

CREATE TABLE questions(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  q TEXT NOT NULL,
  a TEXT NOT NULL,
  incorrect_1 TEXT NOT NULL,
  incorrect_2 TEXT NOT NULL,
  incorrect_3 TEXT NOT NULL,
  book INT REFERENCES books(id),
  chapter INT NOT NULL,
  verse INT,
  difficulty INT NOT NULL
);